name: Build Windows EXE

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'リリースバージョン (例: v1.0.0)'
        required: true
        default: 'v1.0.0'
      release_notes:
        description: 'リリースノート'
        required: false
        default: '新機能と改善点'

jobs:
  build:
    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flet[all] mutagen pyperclip
        
    - name: Build bootloader
      run: |
        git clone https://github.com/pyinstaller/pyinstaller.git
        cd pyinstaller/bootloader
        python ./waf distclean all
        cd ..
        pip install -e .
        
    - name: Build EXE
      run: |
        flet pack .\main.py --name NeCd --onedir --icon .\icon.ico --product-name NeCd --copyright samenoko-112 --hidden-import mutagen -y
    
    - name: zip
      run: |
        Compress-Archive -Path dist/NeCd/* -DestinationPath dist/NeCd-${{ github.event.inputs.version }}.zip
        
    - name: Upload EXE
      uses: actions/upload-artifact@v4
      with:
        name: NeCd
        path: dist/NeCd-${{ github.event.inputs.version }}.zip
        
    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        tag_name: ${{ github.event.inputs.version }}
        name: NeCd ${{ github.event.inputs.version }}
        body: ${{ github.event.inputs.release_notes }}
        draft: true
        prerelease: false
        files: |
          dist/NeCd-${{ github.event.inputs.version }}.zip
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}