name: Build Windows EXE

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flet[all] mutagen pyperclip
        
    - name: Build bootloader
      run: |
        git clone https://github.com/pyinstaller/pyinstaller.git
        cd pyinstaller/bootloader
        python ./waf distclean all
        cd ..
        pip install -e .
        
    - name: Build EXE
      run: |
        flet pack .\main.py --name NeCd --onedir --icon .\icon.ico --product-name NeCd --copyright samenoko-112 --hidden-import mutagen -y
    
    - name: zip
      run: |
        Compress-Archive -Path dist/NeCd/* -DestinationPath dist/NeCd.zip
        
    - name: Upload EXE
      uses: actions/upload-artifact@v4
      with:
        name: NeCd
        path: dist/NeCd.zip